/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import Walkthrough from 'react-native-walkthrough-carousel';

import logo from '../assets/logo.png';

import carousel from './carousel';
import buttons from './buttons';

const styles = {
  backgroundColor: '#eee',
  card: {
    borderColor: '#ddd',
  },
  dotStyle: {
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
  },
  inactiveDotStyle: {
    backgroundColor: '#ddd',
  },
};

export default function App() {
  return (
    <>
      <Walkthrough
        logo={logo}
        carousel={carousel}
        buttons={buttons}
        styles={styles}
      />
    </>
  );
}
